" Configure tab expansion to be 4 spaces.
set tabstop=4
set shiftwidth=4
set expandtab

" Filetype detection
filetype plugin on

" Relative number
set rnu
set nu

" Remap CTRL-w to Leader-w.
nnoremap <Leader>w <C-w>

" Allow switching buffers when there are unsaved changes.
set hidden

" No highlighting all matching searches, please.
set nohls

" Visual cues for my current position.
" - Make the current line number stand out from the relative line numbers.
hi CursorLineNR cterm=bold ctermbg=234 gui=bold guibg=#202020
" Toggle crosshairs.
nnoremap <f2> :set cursorcolumn! <bar> set cursorline! <CR>
"  Make spelling errors stand out even when row is highlighted.
hi SpellBad cterm=underline
" Toggle colorcolumn on/off.
nnoremap <f3> :execute "set colorcolumn=" . (&colorcolumn == "" ? "80" : "")<CR>
hi ColorColumn cterm=bold ctermbg=darkgrey gui=bold guibg=#202020
" Toggle termguicolors
nnoremap <f4> :set termguicolors!<CR>
"Remove all trailing whitespace by pressing F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>"endif

" On my terminal, <s-f8> produces <f20>
nmap <f20> <s-f8>

" Map spellchecking toggle
nnoremap <f9> :setlocal spell! <CR>

" Remap jk to ESC
inoremap jk <esc>

