config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  mercury:
    dotfiles: [f_vimrc, f_bashrc, f_gitconfig, d_nvim]
